### ISSUE TITLE
Controls branch - limelight2 instead of limelight3?

### ISSUE THREAD

**Issue by ejbunnell** [cyberblue234/2024CB234#14]
In the Elevator::CalculateSpeakerAngle(), the limelight being used to detect the distance is the limelight 2. However, it seems that is the limelight on the intake? That's based on the limelight name in Robot.cpp

**Comment by KittenGosCrazy** [comment]
This should be Limelight 3, Limelight 2 is holdover code from when we still had the Limelight 2 mounted in the front
