### ISSUE TITLE
Control branch - Angle direction of shooter

### ISSUE THREAD

**Issue by ejbunnell** [cyberblue234/2024CB234#15]
The comment for Elevator::CalculateSpeakerAngle() says the angle is from parallel to floor, but I am not sure that's what the encoder on the shooter reads as. We need to do some testing to make sure both angles are accurate

**Comment by KittenGosCrazy** [comment]
We could do some math to figure out the angle from floor if we detect from vertical. It should be as simple as getting 90-(angle from vertical)

**Comment by ejbunnell** [comment]
I think we can also make the encoder.SetDistancePerRotation to positive 360 instead of negative, but yeah it shouldn't be hard to fix just going to not work if its wrong
